jQuery(function($){'use strict';$('.mean-menu').meanmenu({meanScreenWidth:'991',});$(window).on('scroll',function(){$(window).scrollTop()>=100?$('.navbar-area').addClass('stickyadd'):$('.navbar-area').removeClass('stickyadd');});$('a.nav-link').on('click',function(e){var $this=$(this);$('html, body').stop().animate({scrollTop:$($this.attr('href')).offset().top-60,},1000);e.preventDefault();});$('.search-btn').on('click',function(){$('.search-popup').toggle(300);});$('.youtube-popup').magnificPopup({disableOn:320,type:'iframe',mainClass:'mfp-fade',removalDelay:160,preloader:false,fixedContentPos:false,});$('.home-slider').owlCarousel({loop:true,margin:0,items:1,smartSpeed:950,});$('.team-slider').owlCarousel({loop:false,margin:15,autoplay:true,autoplayHoverPause:true,autoplayTimeout:8500,smartSpeed:450,responsiveClass:true,responsive:{0:{items:1,},576:{items:2,},768:{items:2,},1000:{items:3,},1400:{items:4}},});$('.gallery-slider').owlCarousel({loop:false,margin:20,autoplay:true,autoplayHoverPause:true,autoplayTimeout:8500,smartSpeed:450,responsiveClass:true,responsive:{0:{items:1,},576:{items:2,},768:{items:3,},1000:{items:3,},},});let testimonialSlider=$('.testimonial-slider').owlCarousel({items:1,dots:true,margin:10,responsiveClass:true,responsive:{0:{items:1,},576:{items:1,},768:{items:1,},1000:{items:1,},},});$('.dot').on('click',function(){testimonialSlider.trigger('to.owl.carousel',[$(this).index(),300]);$('.dot').removeClass('active');$(this).addClass('active');});$('.client-slider').owlCarousel({loop:true,margin:20,items:1,smartSpeed:950,});$('.partner-slider').owlCarousel({loop:true,nav:false,dots:false,smartSpeed:2000,margin:30,autoplayHoverPause:true,autoplay:true,responsive:{0:{items:2,},768:{items:3,},1024:{items:4,},1200:{items:5,},},});$('body').append(`<div class='go-top'><i class='envy envy-angle-up'></i></div>`);$(window).on('scroll',function(){var scrolled=$(window).scrollTop();if(scrolled>600)$('.go-top').addClass('active');if(scrolled<600)$('.go-top').removeClass('active');});$('.go-top').on('click',function(){$('html, body').animate({scrollTop:'0',},500);});function makeTimer(){var endTime=new Date('September 20, 2021 17:00:00 PDT');var endTime=(Date.parse(endTime))/1000;var now=new Date();var now=(Date.parse(now)/1000);var timeLeft=endTime-now;var days=Math.floor(timeLeft/86400);var hours=Math.floor((timeLeft-(days*86400))/3600);var minutes=Math.floor((timeLeft-(days*86400)-(hours*3600))/60);var seconds=Math.floor((timeLeft-(days*86400)-(hours*3600)-(minutes*60)));if(hours<'10'){hours='0'+hours;}
if(minutes<'10'){minutes='0'+minutes;}
if(seconds<'10'){seconds='0'+seconds;}
$('#days').html(days+'<span>Days</span>');$('#hours').html(hours+'<span>Hours</span>');$('#minutes').html(minutes+'<span>Minutes</span>');$('#seconds').html(seconds+'<span>Seconds</span>');}
setInterval(function(){makeTimer();},0);$('.newsletter-form').validator().on('submit',function(event){if(event.isDefaultPrevented()){formErrorSub();submitMSGSub(false,'Please enter your email correctly.');}else{event.preventDefault();}});function callbackFunction(resp){if(resp.result==='success'){formSuccessSub();}else{formErrorSub();}}
function formSuccessSub(){$('.newsletter-form')[0].reset();submitMSGSub(true,'Thank you for subscribing!');setTimeout(function(){$('#validator-newsletter').addClass('hide');},4000)}
function formErrorSub(){$('.newsletter-form').addClass('animated shake');setTimeout(function(){$('.newsletter-form').removeClass('animated shake');},1000)}
function submitMSGSub(valid,msg){if(valid){var msgClasses='validation-success';}else{var msgClasses='validation-danger';}
$('#validator-newsletter').removeClass().addClass(msgClasses).text(msg);}
$('.newsletter-form').ajaxChimp({url:'https://hibootstrap.us20.list-manage.com/subscribe/post?u=60e1ffe2e8a68ce1204cd39a5&amp;id=42d6d188d9',callback:callbackFunction});$(window).on('load',function(e){$('.preloader-main').delay(2000).queue(function(){$(this).remove();});});$('body').append("<a href='https://themeforest.net/checkout/from_item/28749750?license=regular&support=bundle_6month&_ga=2.135854707.317761313.1648883762-918236941.1644836235' target='_blank' class='buy-now-btn'><img src='assets/img/envato.png' alt='envato'/>Buy Now</a>");$('body').append("<div class='switch-box'><label id='switch' class='switch'><input type='checkbox' onchange='toggleTheme()' id='slider'><span class='slider round'></span></label></div>");}(jQuery));function setTheme(themeName){localStorage.setItem('solit_theme',themeName);document.documentElement.className=themeName;}
function toggleTheme(){if(localStorage.getItem('solit_theme')==='theme-dark'){setTheme('theme-light');}else{setTheme('theme-dark');}}
(function(){if(localStorage.getItem('solit_theme')==='theme-dark'){setTheme('theme-dark');document.getElementById('slider').checked=false;}else{setTheme('theme-light');document.getElementById('slider').checked=true;}})();